parameters:
  - name: pool
jobs:
- job: 'Local_JDK'
  pool:
    vmImage: ${{ parameters.pool }}
  steps:
  - template: 'java-tool-installer-local-jdk7-steps.yml'

- job: 'Azure_JDK'
  pool:
    vmImage: ${{ parameters.pool }}
  steps:
  - template: 'java-tool-installer-azure-jdk7-steps.yml'
