jobs:
- job: 'MacOS_Public_Mojave'
  pool:
    vmImage: 'macos-10.14'
  steps:
  - template: src/cocoa-pods/macos-cocoapods-steps.yml

- job: 'MacOS_Public_Catalina'
  pool:
    vmImage: 'macos-10.15'
  steps:
  - template: src/cocoa-pods/macos-cocoapods-steps.yml
