stages:
- stage: 'MacOS_Public_Mojave'
  dependsOn: []
  pool:
    vmImage: 'macos-10.14'
  jobs:
  - template: src/cocoa-pods/macos-cocoapods-steps.yml

- stage: 'MacOS_Public_Catalina'
  dependsOn: []
  pool:
    vmImage: 'macos-10.15'
  jobs:
  - template: src/cocoa-pods/macos-cocoapods-steps.yml
