jobs:
# - job: 'ubuntu_self'
#   pool:
#     name: 'Default'
#     demands:
#     - agent.os -equals Linux
#   steps:
#   - template: src/download-build-artifacts/generate-test-artifacts.yml
#   - template: src/download-build-artifacts/test-download-build-artifacts.yml

# - job: 'macOS_self'
#   pool:
#     name: 'Default'
#     demands:
#     - agent.os -equals Darwin
#   steps:
#   - template: src/download-build-artifacts/generate-test-artifacts.yml
#   - template: src/download-build-artifacts/test-download-build-artifacts.yml

- job: 'win_self'
  pool:
    name: 'Default'
    demands:
    - agent.os -equals Windows_NT
  steps:
  - template: src/download-build-artifacts/generate-test-artifacts.yml
  - template: src/download-build-artifacts/test-download-build-artifacts.yml
  - template: src/download-build-artifacts/test-download-build-artifacts-zip.yml

- job: 'Ubuntu_2004'
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - template: src/download-build-artifacts/generate-test-artifacts.yml
  - template: src/download-build-artifacts/test-download-build-artifacts.yml

- job: 'Ubuntu_1604'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - template: src/download-build-artifacts/generate-test-artifacts.yml
  - template: src/download-build-artifacts/test-download-build-artifacts.yml

- job: 'Ubuntu_1804'
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - template: src/download-build-artifacts/generate-test-artifacts.yml
  - template: src/download-build-artifacts/test-download-build-artifacts.yml

- job: 'VS2019'
  pool:
    vmImage: 'windows-2019'
  steps:
  - template: src/download-build-artifacts/generate-test-artifacts.yml
  - template: src/download-build-artifacts/test-download-build-artifacts.yml
  - template: src/download-build-artifacts/test-download-build-artifacts-zip.yml

- job: 'VS2017_WIN2016'
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - template: src/download-build-artifacts/generate-test-artifacts.yml
  - template: src/download-build-artifacts/test-download-build-artifacts.yml
  - template: src/download-build-artifacts/test-download-build-artifacts-zip.yml

- job: 'MacOS_Public_Catalina'
  pool:
    vmImage: 'macos-10.15'
  steps:
  - template: src/download-build-artifacts/generate-test-artifacts.yml
  - template: src/download-build-artifacts/test-download-build-artifacts.yml

- job: 'MacOS1014'
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - template: src/download-build-artifacts/generate-test-artifacts.yml
  - template: src/download-build-artifacts/test-download-build-artifacts.yml
