jobs:
- job: 'Ubuntu1604'
  pool:
    vm-image: 'ubuntu-16.04'
  steps:
  - template: src/powershell/templates/basic-execution.yml
      parameters:
      useCallOperator: true
  - template: src/powershell/templates/basic-execution.yml
      parameters:
      useCallOperator: false
  - template: src/powershell/templates/global-scope-execution.yml
      parameters:
      useCallOperator: true
  - template: src/powershell/templates/global-scope-execution.yml
      parameters:
      useCallOperator: false

- job: 'Ubuntu1804'
  pool:
    vm-image: 'ubuntu-18.04'
  steps:
  - template: src/powershell/templates/basic-execution.yml
      parameters:
      useCallOperator: true
  - template: src/powershell/templates/basic-execution.yml
      parameters:
      useCallOperator: false
  - template: src/powershell/templates/global-scope-execution.yml
      parameters:
      useCallOperator: true
  - template: src/powershell/templates/global-scope-execution.yml
      parameters:
      useCallOperator: false

- job: 'Ubuntu2004'
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - template: src/powershell/templates/basic-execution.yml
      parameters:
      useCallOperator: true
  - template: src/powershell/templates/basic-execution.yml
      parameters:
      useCallOperator: false
  - template: src/powershell/templates/global-scope-execution.yml
      parameters:
      useCallOperator: true
  - template: src/powershell/templates/global-scope-execution.yml
      parameters:
      useCallOperator: false

- job: 'MacOS1014'
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - template: src/powershell/templates/basic-execution.yml
      parameters:
      useCallOperator: true
  - template: src/powershell/templates/basic-execution.yml
      parameters:
      useCallOperator: false
  - template: src/powershell/templates/global-scope-execution.yml
      parameters:
      useCallOperator: true
  - template: src/powershell/templates/global-scope-execution.yml
      parameters:
      useCallOperator: false

- job: 'MacOS1015'
  pool:
    vmImage: 'macOS-10.15'
  steps:
  - template: src/powershell/templates/basic-execution.yml
      parameters:
      useCallOperator: true
  - template: src/powershell/templates/basic-execution.yml
      parameters:
      useCallOperator: false
  - template: src/powershell/templates/global-scope-execution.yml
      parameters:
      useCallOperator: true
  - template: src/powershell/templates/global-scope-execution.yml
      parameters:
      useCallOperator: false

- job: 'HostedVS2017'
  pool: 
    vm-image: 'vs2017-win2016'
  steps:
  - template: src/powershell/templates/basic-execution.yml
      parameters:
      useCallOperator: true
  - template: src/powershell/templates/basic-execution.yml
      parameters:
      useCallOperator: false
  - template: src/powershell/templates/global-scope-execution.yml
      parameters:
      useCallOperator: true
  - template: src/powershell/templates/global-scope-execution.yml
      parameters:
      useCallOperator: false

- job: 'HostedWindows2019WithVS2019'
  pool:  
    vm-image: 'windows-2019'
  steps:
  - template: src/powershell/templates/basic-execution.yml
      parameters:
      useCallOperator: true
  - template: src/powershell/templates/basic-execution.yml
      parameters:
      useCallOperator: false
  - template: src/powershell/templates/global-scope-execution.yml
      parameters:
      useCallOperator: true
  - template: src/powershell/templates/global-scope-execution.yml
      parameters:
      useCallOperator: false

- job: 'SelfHosted'
  pool:
    name: 'default'
    demands:
    - agent.name -equals test-agent-1
  steps:
  - template: src/powershell/templates/basic-execution.yml
      parameters:
      useCallOperator: true
  - template: src/powershell/templates/basic-execution.yml
      parameters:
      useCallOperator: false
  - template: src/powershell/templates/global-scope-execution.yml
      parameters:
      useCallOperator: true
  - template: src/powershell/templates/global-scope-execution.yml
      parameters:
      useCallOperator: false
