jobs:
- job: 'Ubuntu1604'
  pool:
    vm-image: 'ubuntu-16.04'
  steps:
  - template: src/powershell/templates/basic-execution.yml
  - template: src/powershell/templates/test-scope-execution.yml
    parameters:
      runScriptInSeparateScope: False
  - template: src/powershell/templates/test-scope-execution.yml
    parameters:
      runScriptInSeparateScope: True

- job: 'Ubuntu1804'
  pool:
    vm-image: 'ubuntu-18.04'
  steps:
  - template: src/powershell/templates/basic-execution.yml
  - template: src/powershell/templates/test-scope-execution.yml
    parameters:
      runScriptInSeparateScope: False
  - template: src/powershell/templates/test-scope-execution.yml
    parameters:
      runScriptInSeparateScope: True

- job: 'Ubuntu2004'
  pool:
    vm-image: 'ubuntu-20.04'
  steps:
  - template: src/powershell/templates/basic-execution.yml
  - template: src/powershell/templates/test-scope-execution.yml
    parameters:
      runScriptInSeparateScope: False
  - template: src/powershell/templates/test-scope-execution.yml
    parameters:
      runScriptInSeparateScope: True
- job: 'MacOS1014'
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - template: src/powershell/templates/basic-execution.yml
  - template: src/powershell/templates/test-scope-execution.yml
    parameters:
      runScriptInSeparateScope: False
  - template: src/powershell/templates/test-scope-execution.yml
    parameters:
      runScriptInSeparateScope: True

- job: 'MacOS1015'
  pool:
    vmImage: 'macOS-10.15'
  steps:
  - template: src/powershell/templates/basic-execution.yml
  - template: src/powershell/templates/test-scope-execution.yml
    parameters:
      runScriptInSeparateScope: False
  - template: src/powershell/templates/test-scope-execution.yml
    parameters:
      runScriptInSeparateScope: True

- job: 'HostedVS2017'
  pool: 
    vm-image: 'vs2017-win2016'
  steps:
  - template: src/powershell/templates/basic-execution.yml
  - template: src/powershell/templates/test-scope-execution.yml
    parameters:
      runScriptInSeparateScope: False
  - template: src/powershell/templates/test-scope-execution.yml
    parameters:
      runScriptInSeparateScope: True

- job: 'HostedWindows2019WithVS2019'
  pool:  
    vm-image: 'windows-2019'
  steps:
  - template: src/powershell/templates/basic-execution.yml
  - template: src/powershell/templates/test-scope-execution.yml
    parameters:
      runScriptInSeparateScope: False
  - template: src/powershell/templates/test-scope-execution.yml
    parameters:
      runScriptInSeparateScope: True

- job: 'HostedWindows2019WithVS2019Hosted'
  pool:  
    name: 'default'
  steps:
  - template: src/powershell/templates/basic-execution.yml
  - template: src/powershell/templates/test-scope-execution.yml
    parameters:
      runScriptInSeparateScope: False
  - template: src/powershell/templates/test-scope-execution.yml
    parameters:
      runScriptInSeparateScope: True